#!/bin/bash
xhost +
mkdir -p .eclipse-docker
docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
	   -v $HOME/.Xauthority:/home/developer/.Xauthority --net=host \
           -v `pwd`/eclipse-docker:/home/developer \
           -v `pwd`:/workspace \
           docker-excalibur
