#!/bin/bash

sudo apt update 
sudo apt install docker.io
sudo groupadd docker
sudo usermod -aG docker $USER
su $USER
sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
sudo chmod g+rwx "$HOME/.docker" -R
echo "If installed correctly, the version of docker will appear here:"
docker -v
echo "Installing docker-excalibur, this may take a while..."
docker build docker-excalibur .
echo "Installation successful!"
